# Generated by Django 5.2 on 2025-11-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicPerformance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Roll_No', models.CharField(max_length=20)),
                ('Dept', models.CharField(max_length=100)),
                ('Semester', models.IntegerField()),
                ('Thesis_Work', models.CharField(blank=True, max_length=255, null=True)),
                ('Seminar', models.CharField(blank=True, max_length=255, null=True)),
                ('Internship', models.CharField(blank=True, max_length=255, null=True)),
                ('Project_Presentation', models.CharField(blank=True, max_length=255, null=True)),
                ('SGPA', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('CGPA', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('Backlogs', models.IntegerField(default=0)),
                ('AI_Applications', models.BooleanField(default=False)),
                ('Cloud_Computing', models.BooleanField(default=False)),
                ('Embedded_Systems', models.BooleanField(default=False)),
                ('Cybersecurity', models.BooleanField(default=False)),
                ('Deep_Learning', models.BooleanField(default=False)),
                ('IoT_Systems', models.BooleanField(default=False)),
                ('Big_DataAnalytics', models.BooleanField(default=False)),
                ('Optimization_Techniques', models.BooleanField(default=False)),
                ('Advanced_Algorithms', models.BooleanField(default=False)),
                ('Machine_Learning', models.BooleanField(default=False)),
                ('Data_Analytics', models.BooleanField(default=False)),
                ('Research_Methodology', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'AcademicPerformance',
            },
        ),
        migrations.CreateModel(
            name='ActivityRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Roll_No', models.CharField(max_length=20)),
                ('Dept', models.CharField(max_length=100)),
                ('Library_Hours', models.IntegerField(default=0)),
                ('Books_Borrowed', models.IntegerField(default=0)),
                ('Mock_Test_Score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('Placement_Attendance', models.IntegerField(default=0)),
                ('Internship_Status', models.CharField(choices=[('Completed', 'Completed'), ('Ongoing', 'Ongoing'), ('Not Started', 'Not Started')], default='Not Started', max_length=50)),
                ('Placement_Status', models.CharField(choices=[('Placed', 'Placed'), ('Not Placed', 'Not Placed'), ('In Progress', 'In Progress')], default='Not Placed', max_length=50)),
                ('Company_Name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ActivityRecord',
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Roll_No', models.CharField(max_length=20)),
                ('Dept', models.CharField(max_length=100)),
                ('Semester', models.IntegerField()),
                ('Attendance_Percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Absent_Days', models.IntegerField()),
                ('Medical_Leaves', models.IntegerField(default=0)),
                ('Behaviour_Rating', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
            options={
                'db_table': 'AttendanceRecord',
            },
        ),
        migrations.CreateModel(
            name='DisciplinaryRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Roll_No', models.CharField(max_length=20)),
                ('Action_Taken', models.BooleanField(default=False)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'DisciplinaryRecord',
            },
        ),
        migrations.CreateModel(
            name='FeeRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Roll_No', models.CharField(max_length=20)),
                ('Dept', models.CharField(max_length=100)),
                ('Total_Fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Fee_Paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Fee_Due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Fee_Status', models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Partial', 'Partial')], max_length=50)),
            ],
            options={
                'db_table': 'FeeRecord',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Roll_No', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=100)),
                ('Dept', models.CharField(max_length=100)),
                ('Year', models.IntegerField()),
                ('Semester', models.IntegerField()),
                ('Joined_Year', models.IntegerField()),
                ('Passed_Out_Year', models.IntegerField(blank=True, null=True)),
                ('password', models.CharField(default='student123', max_length=100)),
            ],
            options={
                'db_table': 'Student',
            },
        ),
    ]
