# Generated by Django 5.2 on 2025-11-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicperformance',
            name='AI_Applications',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='academicperformance',
            name='Advanced_Algorithms',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='academicperformance',
            name='Big_DataAnalytics',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='academicperformance',
            name='Cloud_Computing',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='academicperformance',
            name='Cybersecurity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='academicperformance',
            name='Data_Analytics',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='academicperformance',
            name='Deep_Learning',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='academicperformance',
            name='Embedded_Systems',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='academicperformance',
            name='IoT_Systems',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='academicperformance',
            name='Machine_Learning',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='academicperformance',
            name='Optimization_Techniques',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='academicperformance',
            name='Research_Methodology',
            field=models.IntegerField(default=0),
        ),
    ]
