# Generated by Django 5.2.8 on 2025-12-31 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_academicperformance_ai_applications_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academicperformance',
            old_name='Big_DataAnalytics',
            new_name='Big_DataAnalytics',
        ),
        migrations.AlterField(
            model_name='academicperformance',
            name='Internship',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academicperformance',
            name='Project_Presentation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academicperformance',
            name='Seminar',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academicperformance',
            name='Thesis_Work',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academicperformance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='academicperformance',
            table='Academic_Performance_final',
        ),
    ]
